"""Add mechanic_id to service_tickets

Revision ID: d683aae0d001
Revises: 
Create Date: 2025-09-11 12:46:57.123895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd683aae0d001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mechanic_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'mechanics', ['mechanic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('mechanic_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
